name: RoyalAuthPlus
main: org.royaldev.royalauth.RoyalAuth
version: ${pluginversion}
author: jkcclemens
website: http://dev.royaldev.org
description: A security-based plugin that locks player accounts with passwords that must be entered before the player can play.

commands:
  royalauth:
    description: Provides access to administrative functions of the plugin.
    usage: /<command> [subcommands|help]
    aliases: [ra, rauth]
  login:
    description: Logs a player in.
    usage: /<command> [password]
    aliases: [l, logon]
  logout:
    description: Logs a player out.
    usage: /<command>
    aliases: [logoff]
  register:
    description: Registers a player.
    usage: /<command> [password]
  passwd:
    description: Changes a player's password.
    usage: /<command> [oldPassword] [newPassword]

permissions:
  rauth.login:
    description: Allows use of /login
    default: true
  rauth.logout:
    description: Allows use of /logout
    default: true
  rauth.register:
    description: Allows use of /register
    default: true
  rauth.changepassword:
    description: Allows use of /changepassword
    default: true
  rauth.royalauth:
    description: Allows use of /rauth
    default: op
  rauth.user:
    description: Contains all permission nodes for non-administrative functions
    default: false
    children:
      rauth.login: true
      rauth.logout: true
      rauth.register: true
      rauth.changepassword: true
  rauth.*:
    description: Contains every permission node in RoyalAuth
    default: false
    children:
      rauth.user: true
      rauth.royalauth: true
